name: ForgeSoul Bot Test Commit

on:
  workflow_dispatch:

jobs:
  commit-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create test file
      run: echo "Hello from ForgeSoul Bot" > hello-forge-spirit.txt

    - name: Configure Git identity
      run: |
        git config user.name "ForgeSoul Bot"
        git config user.email "forgesoul@example.com"

    - name: Commit file
      run: |
        git add hello-forge-spirit.txt
        git commit -m "ForgeSoul Bot test commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
