name: ForgeSoulBot Verification

on:
  workflow_dispatch:

jobs:
  verify-app-access:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate GitHub App Token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.FORGESOULBOT_APP_ID }}
          installation_id: ${{ secrets.FORGESOULBOT_INSTALLATION_ID }}
          private_key: ${{ secrets.FORGESOULBOT_PRIVATE_KEY }}

      - name: Log Token and Repo Access
        run: |
          echo "Actor: ${{ github.actor }}"
          echo "Token Length: ${#{{ steps.generate_token.outputs.token }}}"
          echo "Repo Slug: ${{ github.repository }}"
