name: ForgeSoulBot Hybrid Test

on:
  workflow_dispatch:

jobs:
  bot-access-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate GitHub App Token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.FORGESOULBOT_APP_ID }}
          installation_id: ${{ secrets.FORGESOULBOT_INSTALLATION_ID }}
          private_key: ${{ secrets.FORGESOULBOT_PRIVATE_KEY }}

      - name: Create test file
        run: echo "Hello from ForgeSoulBot Hybrid Test" > forge-verified.txt

      - name: Configure Git
        run: |
          git config user.name "ForgeSoulBot"
          git config user.email "forgesoulbot@example.com"

      - name: Commit and push file
        env:
          TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          git add forge-verified.txt
          git commit -m "✅ ForgeSoulBot verified and functional"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git HEAD:main
