name: ForgeSoul Bot Push

on:
  workflow_dispatch:

jobs:
  push-with-app-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub App Token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.FORGESOUL_APP_ID }}
          installation_id: ${{ secrets.FORGESOUL_INSTALLATION_ID }}
          private_key: ${{ secrets.FORGESOUL_PRIVATE_KEY }}

      - name: Create signal file
        run: echo "ForgeSoul Bot activated successfully!" > forge-soul-signal.txt

      - name: Commit and push
        run: |
          git config user.name "ForgeSoul Bot"
          git config user.email "forgesoul@example.com"
          git add forge-soul-signal.txt
          git commit -m "Bot signal from ForgeSoul"
          git push
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
